# Generated by Django 4.1.3 on 2023-01-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("nombre_corto", models.CharField(max_length=10)),
                ("imagen", models.ImageField(null=True, upload_to="fotos")),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=150)),
                ("nombre", models.CharField(max_length=150)),
                ("horas", models.IntegerField()),
                ("creditos", models.IntegerField()),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
